app_env: development
port: 8081
context_timeout: 2

mongo:
  db_host: mongodb
  db_port: 27017
  db_user:
  db_pass:
  db_name: auth-service

memcached:
  db_host: memcached
  db_port: 11211

jwt:
  access_token_expiry_hour: 1
  refresh_token_expiry_hour: 24
  access_token_secret: access_token_secret
  refresh_token_secret: refresh_token_secret

grpc_server:
  network: tcp
  port: 8001
  tls: true