version: '3.9'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-service
    container_name: auth-service
    restart: unless-stopped
    env_file: .env
    ports:
      - '$PORT:$PORT'
    depends_on:
      - mongodb
      - memcached

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
    ports:
      - '$DB_PORT:$DB_PORT'
    volumes:
      - dbdata:/data/db

  memcached:
    image: memcached
    container_name: memcached
    restart: unless-stopped
    env_file: .env
    ports:
      - '$MEMCACHED_PORT:$MEMCACHED_PORT'

volumes:
  dbdata:
